# akhq-values.yaml
ingress:
  enabled: false
extraEnv:
  - name: JAVA_OPTS
    value: "-Djava.io.tmpdir=/app"
configuration:
  akhq:
    security:
      default-group: no-roles
      basic-auth:
      - username: admin
        password: "6a336794f1c6a705da1eaedca40f645c954152cf45c67f347bb47e2e7765fa7f"
        groups:
        - admin
    connections:
      poc-kafka:
        properties:
          bootstrap.servers: poc-kafka-kafka-bootstrap:9092
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access
      customHttpResponseHeaders:
      - name: "Content-Security-Policy"
        value: "default-src 'self';"
      - name: "Content-Security-Policy"
        value: "script-src 'self' 'sha256-8MRcSA/0obaf+0ty4aHBYLw8yHUD7pG5ZuAe6h/jgeE=' 'sha256-gJJbEuYmJ8XKCDxko0yeA3kohpu8CjXhUGP67iBzkII=' 'sha256-OhIMElhi3dn7/J5RBkfiH9E3dXTFVA4BU0hqYTbrOl8=';"
      - name: "Content-Security-Policy"
        value: "style-src 'self' 'sha256-FwvOtgZ7bxcVaY5ak4eAM0Ullk2Ynq5iSZvlKgw932M=' 'sha256-gixU7LtMo8R4jqjOifcbHB/dd61eJUxZHCC6RXtUKOQ=' 'sha256-Dn0vMZLidJplZ4cSlBMg/F5aa7Vol9dBMHzBF4fGEtk=' 'sha256-sA0hymKbXmMTpnYi15KmDw4u6uRdLXqHyoYIaORFtjU=' 'sha256-pj9V2e6V+tHTbTuA1l5A4YkKnf+RLlV5+E8an9SA5D4=' 'sha256-DnjfEfMjygXpW+KOCmSS83GQLz9DzlfnL0GKP3el+aI=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=';"
      - name: "Content-Security-Policy"
        value: "img-src 'self' data: ;"
      - name: "X-Permitted-Cross-Domain-Policies"
        value: "none"
      - name: "X-Frame-Options"
        value: "SAMEORIGIN"
      - name: "Strict-Transport-Security"
        value: "max-age=31536000"
    pagination:
      page-size: 25
      threads: 16
    avro-serializer:
      json.serialization.inclusions:
        - NON_NULL
    topic:
      retention: 7200000 # default retention period when creating topic
      partition: 3 #  default number of partition when creating topic
      replication: 3 # default number of replicas when creating topic
      internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
        - "^.*_schemas$"
        - "^.*connect-config$"
        - "^.*connect-offsets$"
        - "^.*connect-status$"
        - "^.*__consumer_offsets$"
        - "^.*trace$"
        - "^.*dms_dial_test$"
      stream-regexps: # list of regexp to be considered as internal stream topic
        - "^.*-changelog$"
        - "^.*-repartition$"
        - "^.*-rekey$"
      skip-consumer-groups: false
      skip-last-record: false
      show-all-consumer-groups: false
      retry:
        topic-exists: # Delay between retries when checking for existence of newly created topics. This is needed as it might take the kafka broker a few seconds to create new topics.
          delay: "3s"
    topic-data:
      size: 50
      poll-timeout: 1000
      kafka-max-message-length: 1000000
    ui-options:
      topic:
        default-view: HIDE_INTERNAL  # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM). Overrides default
        skip-consumer-groups: false # Skip loading consumer group information when showing topics. Overrides default
        skip-last-record: true  # Skip loading last record date information when showing topics.  Overrides default
        show-all-consumer-groups: true # Expand list of consumer groups instead of showing one. Overrides default.
      topic-data:
        sort: NEWEST # default sort order (OLDEST, NEWEST) (default: OLDEST).  Overrides default
  micronaut:
    server:
      context-path: /akhq
    security:
      enabled: true
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: "2d41b8e142b6b4339b96ff88d1c462d61f4eafb64797ed76506fd0339515217d"
readinessProbe:
  enabled: true
  prefix: "/akhq" # set same as `micronaut.server.context-path`
  path: /health
  port: management
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  httpGetExtra: {}

livenessProbe:
  enabled: true
  prefix: "/akhq" # set same as `micronaut.server.context-path`
  path: /health
  port: management
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  httpGetExtra: {}
