apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: poc-cluster-dr
  namespace: poc-cluster
spec:
  host: poc-cluster
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: poc-cluster-dashboards-dr
  namespace: poc-cluster
spec:
  host: poc-cluster-dashboards
  trafficPolicy:
    tls:
      mode: DISABLE
      insecureSkipVerify: true
