apiVersion: v1
kind: Secret
metadata:
  name: opensearch-admin
  namespace: poc-cluster
type: Opaque
stringData:
  username: admin
  password: <password>

---
apiVersion: v1
kind: Secret
metadata:
  name: akhq-secret
  namespace: poc-cluster
type: Opaque
stringData:
  application.yml: |
    akhq:
      security:
        default-group: no-roles
        basic-auth:
          - username: admin
            password: <password sha256 (default) or bcrypt>
            groups:
              - admin
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-azure-credentials
  namespace: poc-cluster
type: Opaque
stringData:
  azure.client.default.account: pocpatchsta001
  azure.client.default.key: <your-account-key>
