apiVersion: v1
kind: Secret
metadata:
  name: opensearch-admin
  namespace: poc-cluster
type: Opaque
stringData:
  username: admin
  password: Infr@30032026

---
apiVersion: v1
kind: Secret
metadata:
  name: akhq-secret
  namespace: poc-cluster
type: Opaque
stringData:
  application.yml: |
    akhq:
      security:
        default-group: no-roles
        basic-auth:
          - username: admin
            password: "$2y$12$FnVSiVO3x/VMrzSmAPHuoedqxHjtK/5v3aHw3RSLQN0j1efYt85jS"
            groups:
              - admin
