apiVersion: opensearch.org/v1
kind: OpenSearchCluster
metadata:
  name: poc-cluster
  namespace: poc-cluster
spec:
  general:
    serviceName: poc-cluster
    version: "3.5.0"
    httpPort: 9200
    vendor: opensearch
    drainDataNodes: true
    pluginsList:
      - "repository-azure"
      - "repository-s3"
    keystore:
      - secret:
          name: opensearch-azure-credentials
        keyMappings:
          azure.client.default.account: azure.client.default.account
          azure.client.default.key: azure.client.default.key
  security:
    config:
      adminCredentialsSecret:
        name: opensearch-admin
    tls:
      http:
        generate: true
      transport:
        generate: true
        perNode: true

  dashboards:
    enable: true
    version: "3.5.0"
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "500m"

  nodePools:
    - component: masters
      replicas: 3
      diskSize: "20Gi"
      roles:
        - "cluster_manager"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
      jvm: "-Xmx1024m -Xms1024m"
#      persistence:
#        storageClass: "standard"
       additionalInitContainers:
        - name: keystore-setup
          image: opensearchproject/opensearch:3.5.0
          command:
            - bash
            - -c
            - |
              bin/opensearch-keystore create -p || true
              cat /azure-creds/azure.client.default.account | \
                bin/opensearch-keystore add --stdin --force azure.client.default.account
              cat /azure-creds/azure.client.default.key | \
                bin/opensearch-keystore add --stdin --force azure.client.default.key
              cp config/opensearch.keystore /keystore-volume/opensearch.keystore
          volumeMounts:
            - name: azure-creds
              mountPath: /azure-creds
            - name: keystore-volume
              mountPath: /keystore-volume
        additionalVolumes:
        - name: keystore-volume
          emptyDir: {}
          path: /usr/share/opensearch/config
          restartPods: false
          
    - component: data
      replicas: 3
      diskSize: "50Gi"
      roles:
        - "data"
        - "ingest"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
      jvm: "-Xmx2048m -Xms2048m"
#      persistence:
#        storageClass: "standard"
      additionalInitContainers:
        - name: keystore-setup
          image: opensearchproject/opensearch:3.5.0
          command:
            - bash
            - -c
            - |
              bin/opensearch-keystore create -p || true
              cat /azure-creds/azure.client.default.account | \
                bin/opensearch-keystore add --stdin --force azure.client.default.account
              cat /azure-creds/azure.client.default.key | \
                bin/opensearch-keystore add --stdin --force azure.client.default.key
              cp config/opensearch.keystore /keystore-volume/opensearch.keystore
          volumeMounts:
            - name: azure-creds
              mountPath: /azure-creds
            - name: keystore-volume
              mountPath: /keystore-volume
      additionalVolumes:
        - name: keystore-volume
          emptyDir: {}
          path: /usr/share/opensearch/config
          restartPods: false
