apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: poc-tls
  namespace: istio-system
spec:
  secretName: poc-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: "openpoc.dpdns.org"
  dnsNames:
    - "openpoc.dpdns.org"
    - "*.openpoc.dpdns.org"
  duration: 8760h
  renewBefore: 720h
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: poc-dashboards-tls
  namespace: istio-system          # ต้องอยู่ใน istio-system เพราะ Gateway อ่านจากที่นี่
spec:
  secretName: poc-dashboards-tls   # ชื่อ Secret ที่ cert-manager จะสร้างให้
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: "poc.internal"
  dnsNames:
    - "opensearch.poc.internal"
    - "dashboards.poc.internal"
  duration: 8760h                  # 1 ปี
  renewBefore: 720h                # renew ก่อน expire 30 วัน
